# Dependabot configuration for Hugo website
version: 2
updates:
  # Update GitHub Actions used in workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "lhoupert"  # Replace with your GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"

  # Update Go modules (Hugo theme dependencies)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"  
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "lhoupert"  # Replace with your GitHub username
    commit-message:
      prefix: "deps"
      include: "scope"
    # Group Hugo theme updates
    groups:
      hugo-theme:
        patterns:
          - "github.com/jpanther/congo*"
